version: '3.7'

volumes:
    frete-mysql-data: null

networks:
    frete-net: null

services:
    db:
        image: mysql:8.0
        container_name: frete-db
        volumes:
            - frete-mysql-data:/var/lib/mysql
        ports:
            - 3001:3306
        networks:
            - frete-net
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - TZ=America/Sao_Paulo
        restart: always

    app:
        container_name: frete-app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - db
        volumes:
            - .:/app
        ports:
            - 80:80
        networks:
            - frete-net
        restart: always
